version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eli_test_strips
      POSTGRES_USER: eli_user
      POSTGRES_PASSWORD: eli_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://eli_user:eli_password@postgres:5432/eli_test_strips
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres

volumes:
  postgres_data: